class Placeholders:
    MENU="Menu"
    LOAD_MODELS="Load models"
    SHOW_RANKING="Show models ranking"
    TRAIN="Train models"
    CLASSIFIER_LABEL = "Classifier: None"
    VECTORIZER_LABEL = "Vectorizer: None"
    REVIEW_LABEL = "Your Review:"
    WRITE_STH = "Write your review here..."
    CLEAR = "Clear"
    PROCESS_REVIEW ="Process Review"
    REVIEW_INFO ="Review Information"
    MODEL_LOADED ="Model Loaded"
    APP_NAME ="Review App"
    TRAINING_PROG_CDN="Training models, please wait..."
    TRAINING_PROG ="Training in Progress"
    TRAINING_COMPLETED="Training Completed"
    FILE_SELECTED="File Selected"
